### ISSUE TITLE
Wrong indexes in graphics implementation

### ISSUE THREAD

**Issue by KaboomPhysicist** [laurarangot5/Hyperbolic-dif-eq#9]
I'm almost sure that the indexes are wrong in

```
for(int i = 0; i < m+1; i++){
                W.push_back(w.at(i).at(value_pos));
                t.push_back(time.at(i));                
        }
```
and 
```
for(int i = 0; i < m+1; i++){
            W.push_back(w.at(i));}
```

and (this one explains the wrong distribution of ticks when plotting)
```
plt::xticks(time);
plt::yticks(pos);
```
From the implementation in Burden (Alg. 12.4), we know that the first index of the solution (rows) $i = 0,...,m$ and the second index (columns) $j=0,...,n$. If we check the original definitions of m and n, we find that m and n are the sizes for x and t meshes respectively. It means that if we want a fixed position, we must fix the index $i$, but the first for loop in this issue is related to fixed position and the variation is given for this index.

If you want more proofs for the wrong indexing, you could check ```HyperbolicSolver::print_table()``` function where the indexing was previously tested printing with the corresponding variable at the same time.

Furthermore, I don't see the necessity for building the vector t in the first loop. As long as I can see, t and time are equal, so this is a memory leakage.

**Comment by laurarangot5** [comment]
I woulnd't want to work for you beacuse your issues are kind of mean. 

You are wright about the idex, however it has nothig to do with the ticks problem.
